CREATE TABLE users (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nickname VARCHAR(100) NOT NULL,
email VARCHAR(255) NOT NULL,
active BOOLEAN NOT NULL DEFAULT TRUE,
created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_users_nickname_not_blank
       CHECK (BTRIM(nickname) <> ''),

    CONSTRAINT chk_users_email_not_blank
       CHECK (BTRIM(email) <> '')
);

    CREATE UNIQUE INDEX ux_users_nickname_ci
        ON users (LOWER(BTRIM(nickname)));

    CREATE UNIQUE INDEX ux_users_email_ci
        ON users (LOWER(BTRIM(email)));