CREATE TABLE orders (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id BIGINT NOT NULL,
status VARCHAR(30) NOT NULL,
total_amount NUMERIC(12, 2) NOT NULL,
created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id)
            REFERENCES users(id),

    CONSTRAINT chk_orders_total_amount
        CHECK (total_amount >= 0),

    CONSTRAINT chk_orders_status
        CHECK (status IN (
              'CREATED',
              'PAID',
              'CANCELLED',
              'COMPLETED'
            ))
);


CREATE TABLE order_items (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
order_id BIGINT NOT NULL,
product_id BIGINT NOT NULL,
quantity INTEGER NOT NULL,
unit_price NUMERIC(12, 2) NOT NULL,

     CONSTRAINT fk_order_items_order
         FOREIGN KEY (order_id)
             REFERENCES orders(id)
             ON DELETE CASCADE,

     CONSTRAINT fk_order_items_product
         FOREIGN KEY (product_id)
             REFERENCES products(id),

     CONSTRAINT chk_order_items_quantity
         CHECK (quantity > 0),

     CONSTRAINT chk_order_items_unit_price
         CHECK (unit_price >= 0)
);


CREATE INDEX idx_orders_user_id
    ON orders(user_id);

CREATE INDEX idx_order_items_order_id
    ON order_items(order_id);

CREATE INDEX idx_order_items_product_id
    ON order_items(product_id);