services:
  product-db:
    image: postgres:17
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_password
    ports:
      - "5433:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U product_user -d product_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  user-db:
    image: postgres:17
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_password
    ports:
      - "5434:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_user -d user_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  order-db:
    image: postgres:17
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_password
    ports:
      - "5435:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_user -d order_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  product-service:
    build:
      context: ./product-service
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:postgresql://product-db:5432/product_db
      DB_USERNAME: product_user
      DB_PASSWORD: product_password
    depends_on:
      product-db:
        condition: service_healthy

  user-service:
    build:
      context: ./user-service
    ports:
      - "8082:8082"
    environment:
      DB_URL: jdbc:postgresql://user-db:5432/user_db
      DB_USERNAME: user_user
      DB_PASSWORD: user_password
    depends_on:
      user-db:
        condition: service_healthy

  order-service:
    build:
      context: ./order-service
    ports:
      - "8083:8083"
    environment:
      DB_URL: jdbc:postgresql://order-db:5432/order_db
      DB_USERNAME: order_user
      DB_PASSWORD: order_password

      USER_SERVICE_URL: http://user-service:8082
      PRODUCT_SERVICE_URL: http://product-service:8081

    depends_on:
      order-db:
        condition: service_healthy
      product-service:
        condition: service_started
      user-service:
        condition: service_started

volumes:
  product-db-data:
  user-db-data:
  order-db-data:
