spring:
  application:
    name: api-gateway

  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/realms/spring-shop}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8080/realms/spring-shop/protocol/openid-connect/certs}

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-read
              uri: lb://product-service
              predicates:
                - Path=/products,/products/**
                - Method=GET

            - id: product-create
              uri: lb://product-service
              predicates:
                - Path=/products
                - Method=POST

            - id: product-update
              uri: lb://product-service
              predicates:
                - Path=/products/*
                - Method=PUT

            - id: product-delete
              uri: lb://product-service
              predicates:
                - Path=/products/*
                - Method=DELETE

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders,/orders/**


server:
  port: 8085


management:
  server:
    port: 9085

  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

  endpoint:
    health:
      show-details: always

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true


  tracing:
    sampling:
      probability: 1.0

  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}

    tracing:
      export:
        otlp:
          endpoint: ${OTEL_TRACES_ENDPOINT:http://localhost:4318/v1/traces}
          transport: http

logging:
  structured:
    format:
      console: ecs
