spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/realms/spring-shop}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8080/realms/spring-shop/protocol/openid-connect/certs}

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-read
              uri: ${PRODUCT_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/products,/products/**
                - Method=GET

            - id: product-create
              uri: ${PRODUCT_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/products
                - Method=POST

            - id: product-update
              uri: ${PRODUCT_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/products/*
                - Method=PUT

            - id: product-delete
              uri: ${PRODUCT_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/products/*
                - Method=DELETE

            - id: order-service
              uri: ${ORDER_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/orders,/orders/**


server:
  port: 8085


management:
  server:
    port: 9085

  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

  endpoint:
    health:
      show-details: always

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true