CREATE TABLE order_creation_sagas (
  id UUID PRIMARY KEY,

  user_id BIGINT NOT NULL,

  order_id BIGINT,

  status VARCHAR(40) NOT NULL,

  failure_reason VARCHAR(1000),

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_order_creation_sagas_order
      FOREIGN KEY (order_id)
          REFERENCES orders(id)
          ON DELETE SET NULL,

  CONSTRAINT uq_order_creation_sagas_order
      UNIQUE (order_id),

  CONSTRAINT chk_order_creation_sagas_status
      CHECK (
          status IN (
                     'STARTED',
                     'RESERVING_STOCK',
                     'STOCK_RESERVED',
                     'COMPLETING_ORDER',
                     'COMPLETED',
                     'COMPENSATING',
                     'COMPENSATED',
                     'COMPENSATION_FAILED',
                     'FAILED'
              )
          )
);

CREATE INDEX idx_order_creation_sagas_status
    ON order_creation_sagas(status);


CREATE TABLE order_creation_saga_reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  saga_id UUID NOT NULL,

  product_id BIGINT NOT NULL,

  quantity INTEGER NOT NULL,

  reservation_key UUID NOT NULL,

  item_index INTEGER NOT NULL,

  status VARCHAR(40) NOT NULL,

  unit_price NUMERIC(12, 2),

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_order_creation_saga_reservations_saga
      FOREIGN KEY (saga_id)
          REFERENCES order_creation_sagas(id)
          ON DELETE CASCADE,

  CONSTRAINT uq_order_creation_saga_reservation_key
      UNIQUE (reservation_key),

  CONSTRAINT uq_order_creation_saga_item_index
      UNIQUE (saga_id, item_index),

  CONSTRAINT chk_order_creation_saga_quantity
      CHECK (quantity > 0),

  CONSTRAINT chk_order_creation_saga_reservation_status
      CHECK (
          status IN (
                     'PLANNED',
                     'RESERVED',
                     'RESERVATION_FAILED',
                     'RELEASED'
              )
          ),

  CONSTRAINT chk_order_creation_saga_unit_price
      CHECK (
          unit_price IS NULL
              OR unit_price >= 0
          )
);

CREATE INDEX idx_order_creation_saga_reservations_saga
    ON order_creation_saga_reservations(saga_id);

CREATE INDEX idx_order_creation_saga_reservations_status
    ON order_creation_saga_reservations(status);