spring:
  application:
    name: order-service

  http:
    clients:
      connect-timeout: 2s
      read-timeout: 2s

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/order_db}
    username: ${DB_USERNAME:order_user}
    password: ${DB_PASSWORD:order_password}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


server:
  port: 8083


services:
  user:
    url: ${USER_SERVICE_URL:http://localhost:8082}

  product:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8081}


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,circuitbreakers,circuitbreakerevents,retries,retryevents

  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      productService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        event-consumer-buffer-size: 20

        record-exceptions:
          - pl.chrisitstyle.order.exception.ExternalServiceException

        ignore-exceptions:
          - pl.chrisitstyle.order.exception.OrderCreationException


  retry:
    instances:
      userService:
        max-attempts: 3
        wait-duration: 300ms
        event-consumer-buffer-size: 20

        retry-exceptions:
          - pl.chrisitstyle.order.exception.ExternalServiceException

        ignore-exceptions:
          - pl.chrisitstyle.order.exception.OrderCreationException


      productService:
        max-attempts: 3
        wait-duration: 300ms
        event-consumer-buffer-size: 20

        retry-exceptions:
          - pl.chrisitstyle.order.exception.ExternalServiceException

        ignore-exceptions:
          - pl.chrisitstyle.order.exception.OrderCreationException


      productServiceRelease:
        max-attempts: 3
        wait-duration: 300ms
        event-consumer-buffer-size: 20

        retry-exceptions:
          - pl.chrisitstyle.order.exception.ExternalServiceException

        ignore-exceptions:
          - pl.chrisitstyle.order.exception.OrderCreationException