spring:
  application:
    name: product-service

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connect-timeout: 2s
      timeout: 2s


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/realms/spring-shop}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8080/realms/spring-shop/protocol/openid-connect/certs}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/product_db}
    username: ${DB_USERNAME:product_user}
    password: ${DB_PASSWORD:product_password}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true


server:
  port: 8081


management:
  observations:
    enable:
      spring:
        security: false
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0

  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}

    tracing:
      export:
        otlp:
          endpoint: ${OTEL_TRACES_ENDPOINT:http://localhost:4318/v1/traces}
          transport: http

  otlp:
    metrics:
      export:
        enabled: false

logging:
  structured:
    format:
      console: ecs

app:
  release-version: ${RELEASE_VERSION:stable}