apiVersion: v1
kind: Service

metadata:
  name: order-db
  namespace: spring-shop

spec:
  clusterIP: None

  selector:
    app: order-db

  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: order-db
  namespace: spring-shop

spec:
  serviceName: order-db
  replicas: 1

  selector:
    matchLabels:
      app: order-db

  template:
    metadata:
      labels:
        app: order-db

    spec:
      containers:
        - name: postgres
          image: postgres:17

          ports:
            - name: postgres
              containerPort: 5432

          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: spring-shop-config
                  key: ORDER_DB_NAME

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: spring-shop-secrets
                  key: ORDER_DB_USERNAME

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-shop-secrets
                  key: ORDER_DB_PASSWORD

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - name: order-db-data
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
    - metadata:
        name: order-db-data

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi
