apiVersion: v1
kind: ConfigMap

metadata:
  name: spring-shop-config
  namespace: spring-shop

data:
  PRODUCT_DB_NAME: product_db
  USER_DB_NAME: user_db
  ORDER_DB_NAME: order_db
  NOTIFICATION_DB_NAME: notification_db
  KEYCLOAK_DB_NAME: keycloak

  PRODUCT_DB_URL: jdbc:postgresql://product-db:5432/product_db
  USER_DB_URL: jdbc:postgresql://user-db:5432/user_db
  ORDER_DB_URL: jdbc:postgresql://order-db:5432/order_db
  NOTIFICATION_DB_URL: jdbc:postgresql://notification-db:5432/notification_db
  KEYCLOAK_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak

  PRODUCT_SERVICE_URL: http://product-service:8081
  USER_SERVICE_URL: http://user-service:8082
  ORDER_SERVICE_URL: http://order-service:8083

  KAFKA_BOOTSTRAP_SERVERS: kafka:19092

  JWT_ISSUER_URI: http://localhost:8080/realms/spring-shop
  JWT_JWK_SET_URI: http://keycloak:8080/realms/spring-shop/protocol/openid-connect/certs

  KEYCLOAK_TOKEN_URI: http://keycloak:8080/realms/spring-shop/protocol/openid-connect/token

  OTEL_TRACES_ENDPOINT: http://tempo:4318/v1/traces

  MANAGEMENT_OBSERVATIONS_ENABLE_SPRING_SECURITY: "false"

  REDIS_HOST: redis
  REDIS_PORT: "6379"
